const BK_Maps = [
	{ name: "SM_SPIRAL_MOUNTAIN", pointer: "", sceneID: "1", modelAPointer: "14CF", modelBPointer: "14D0" },
	{ name: "SM_BANJOS_HOUSE", pointer: "", sceneID: "8C", modelAPointer: "14A2", modelBPointer: "14A4" },
	{ name: "MM_MUMBOS_MOUNTAIN", pointer: "", sceneID: "2", modelAPointer: "14AA", modelBPointer: "14AB" },
	{ name: "MM_TICKERS_TOWER", pointer: "", sceneID: "C", modelAPointer: "14AC", modelBPointer: "14AD" },
	{ name: "MM_MUMBOS_SKULL", pointer: "", sceneID: "E", modelAPointer: "14AE", modelBPointer: "" },
	{ name: "TTC_TREASURE_TROVE_COVE", pointer: "", sceneID: "7", modelAPointer: "146B", modelBPointer: "146C" },
	{ name: "TTC_BLUBBERS_SHIP", pointer: "", sceneID: "5", modelAPointer: "146F", modelBPointer: "1470" },
	{ name: "TTC_NIPPERS_SHELL", pointer: "", sceneID: "6", modelAPointer: "146D", modelBPointer: "146E" },
	{ name: "TTC_SHARKFOOD_ISLAND", pointer: "", sceneID: "8F", modelAPointer: "1473", modelBPointer: "" },
	{ name: "TTC_SANDCASTLE", pointer: "", sceneID: "A", modelAPointer: "1471", modelBPointer: "1472" },
	{ name: "CC_CLANKERS_CAVERN", pointer: "", sceneID: "B", modelAPointer: "14ED", modelBPointer: "14EE" },
	{ name: "CC_WITCH_SWITCH_ROOM", pointer: "", sceneID: "21", modelAPointer: "14EF", modelBPointer: "" },
	{ name: "CC_INSIDE_CLANKER", pointer: "", sceneID: "22", modelAPointer: "14F0", modelBPointer: "14F1" },
	{ name: "CC_GOLDFEATHER_ROOM", pointer: "", sceneID: "23", modelAPointer: "14F2", modelBPointer: "" },
	{ name: "BGS_BUBBLEGLOOP_SWAMP", pointer: "", sceneID: "D", modelAPointer: "14D1", modelBPointer: "14D2" },
	{ name: "BGS_MR_VILE", pointer: "", sceneID: "10", modelAPointer: "14D3", modelBPointer: "" },
	{ name: "BGS_TIPTUP", pointer: "", sceneID: "11", modelAPointer: "14D4", modelBPointer: "14D5" },
	{ name: "BGS_MUMBOS_SKULL", pointer: "", sceneID: "47", modelAPointer: "14AE", modelBPointer: "" },
	{ name: "GV_GOBIS_VALLEY", pointer: "", sceneID: "12", modelAPointer: "1474", modelBPointer: "1475" },
	{ name: "GV_SNS_CHAMBER", pointer: "", sceneID: "92", modelAPointer: "147E", modelBPointer: "" },
	{ name: "GV_MEMORY_GAME", pointer: "", sceneID: "13", modelAPointer: "1476", modelBPointer: "" },
	{ name: "GV_SANDYBUTTS_MAZE", pointer: "", sceneID: "14", modelAPointer: "1478", modelBPointer: "1479" },
	{ name: "GV_WATER_PYRAMID", pointer: "", sceneID: "15", modelAPointer: "147A", modelBPointer: "147B" },
	{ name: "GV_RUBEES_CHAMBER", pointer: "", sceneID: "16", modelAPointer: "147C", modelBPointer: "" },
	{ name: "GV_INSIDE_JINXY", pointer: "", sceneID: "1A", modelAPointer: "147D", modelBPointer: "" },
	{ name: "FP_FREEZEEZY_PEAK", pointer: "", sceneID: "27", modelAPointer: "14C8", modelBPointer: "14C9" },
	{ name: "FP_BOGGYS_IGLOO", pointer: "", sceneID: "41", modelAPointer: "14CA", modelBPointer: "14CE" },
	{ name: "FP_WOZZAS_CAVE", pointer: "", sceneID: "7F", modelAPointer: "14CC", modelBPointer: "14CD" },
	{ name: "FP_MUMBOS_SKULL", pointer: "", sceneID: "48", modelAPointer: "14AE", modelBPointer: "" },
	{ name: "FP_CHRISTMAS_TREE", pointer: "", sceneID: "53", modelAPointer: "14CB", modelBPointer: "" },
	{ name: "MMM_MAD_MONSTER_MANSION", pointer: "", sceneID: "1B", modelAPointer: "147F", modelBPointer: "1480" },
	{ name: "MMM_CHURCH", pointer: "", sceneID: "1C", modelAPointer: "1486", modelBPointer: "1487" },
	{ name: "MMM_CELLAR", pointer: "", sceneID: "1D", modelAPointer: "1482", modelBPointer: "149B" },
	{ name: "MMM_TUMBLARS_SHED", pointer: "", sceneID: "24", modelAPointer: "1488", modelBPointer: "" },
	{ name: "MMM_WELL", pointer: "", sceneID: "25", modelAPointer: "1495", modelBPointer: "1496" },
	{ name: "MMM_NAPPERS_ROOM", pointer: "", sceneID: "26", modelAPointer: "1485", modelBPointer: "149A" },
	{ name: "MMM_EGG_ROOM", pointer: "", sceneID: "28", modelAPointer: "1489", modelBPointer: "148A" },
	{ name: "MMM_NOTE_ROOM", pointer: "", sceneID: "29", modelAPointer: "148B", modelBPointer: "148C" },
	{ name: "MMM_FEATHER_ROOM", pointer: "", sceneID: "2A", modelAPointer: "148D", modelBPointer: "148E" },
	{ name: "MMM_SECRET_CHURCH_ROOM", pointer: "", sceneID: "2B", modelAPointer: "1483", modelBPointer: "1484" },
	{ name: "MMM_BATHROOM", pointer: "", sceneID: "2C", modelAPointer: "148F", modelBPointer: "1490" },
	{ name: "MMM_BEDROOM", pointer: "", sceneID: "2D", modelAPointer: "1491", modelBPointer: "1492" },
	{ name: "MMM_HONEYCOMB_ROOM", pointer: "", sceneID: "2E", modelAPointer: "1493", modelBPointer: "1494" },
	{ name: "MMM_WATERDRAIN_BARREL", pointer: "", sceneID: "2F", modelAPointer: "1481", modelBPointer: "1497" },
	{ name: "MMM_MUMBOS_SKULL", pointer: "", sceneID: "30", modelAPointer: "14AE", modelBPointer: "" },
	{ name: "MMM_INSIDE_LOGGO", pointer: "", sceneID: "8D", modelAPointer: "1498", modelBPointer: "1499" },
	{ name: "RBB_RUSTY_BUCKET_BAY", pointer: "", sceneID: "31", modelAPointer: "14B0", modelBPointer: "14B1" },
	{ name: "RBB_ANCHOR_ROOM", pointer: "", sceneID: "8B", modelAPointer: "14C5", modelBPointer: "14C6" },
	{ name: "RBB_ENGINE_ROOM", pointer: "", sceneID: "34", modelAPointer: "14B2", modelBPointer: "14B3" },
	{ name: "RBB_WAREHOUSE", pointer: "", sceneID: "35", modelAPointer: "14B4", modelBPointer: "14B5" },
	{ name: "RBB_BOATHOUSE", pointer: "", sceneID: "36", modelAPointer: "14B6", modelBPointer: "14B7" },
	{ name: "RBB_CONTAINER_1", pointer: "", sceneID: "37", modelAPointer: "14B8", modelBPointer: "" },
	{ name: "RBB_CONTAINER_3", pointer: "", sceneID: "38", modelAPointer: "14BA", modelBPointer: "" },
	{ name: "RBB_CREW_CABIN", pointer: "", sceneID: "39", modelAPointer: "14BD", modelBPointer: "" },
	{ name: "RBB_BOSS_BOOM_BOX", pointer: "", sceneID: "3A", modelAPointer: "14BE", modelBPointer: "14BF" },
	{ name: "RBB_STORAGE_ROOM", pointer: "", sceneID: "3B", modelAPointer: "14C1", modelBPointer: "14C2" },
	{ name: "RBB_KITCHEN", pointer: "", sceneID: "3C", modelAPointer: "14C3", modelBPointer: "14C4" },
	{ name: "RBB_NAVIGATION_ROOM", pointer: "", sceneID: "3D", modelAPointer: "14C0", modelBPointer: "14C7" },
	{ name: "RBB_CONTAINER_2", pointer: "", sceneID: "3E", modelAPointer: "14B9", modelBPointer: "" },
	{ name: "RBB_CAPTAINS_CABIN", pointer: "", sceneID: "3F", modelAPointer: "14BB", modelBPointer: "14BC" },
	{ name: "CCW_HUB", pointer: "", sceneID: "40", modelAPointer: "14D8", modelBPointer: "14E3" },
	{ name: "CCW_SPRING", pointer: "", sceneID: "43", modelAPointer: "14D9", modelBPointer: "14E4" },
	{ name: "CCW_SUMMER", pointer: "", sceneID: "44", modelAPointer: "14DA", modelBPointer: "14E5" },
	{ name: "CCW_AUTUMN", pointer: "", sceneID: "45", modelAPointer: "14DB", modelBPointer: "14E6" },
	{ name: "CCW_WINTER", pointer: "", sceneID: "46", modelAPointer: "14DC", modelBPointer: "14E7" },
	{ name: "CCW_SPRING_MUMBOS_SKULL", pointer: "", sceneID: "4A", modelAPointer: "14AE", modelBPointer: "" },
	{ name: "CCW_SUMMER_MUMBOS_SKULL", pointer: "", sceneID: "4B", modelAPointer: "14AE", modelBPointer: "" },
	{ name: "CCW_AUTUMN_MUMBOS_SKULL", pointer: "", sceneID: "4C", modelAPointer: "14AE", modelBPointer: "" },
	{ name: "CCW_WINTER_MUMBOS_SKULL", pointer: "", sceneID: "4D", modelAPointer: "14AE", modelBPointer: "" },
	{ name: "CCW_SUMMER_ZUBBA_HIVE", pointer: "", sceneID: "5A", modelAPointer: "14DD", modelBPointer: "" },
	{ name: "CCW_SPRING_ZUBBA_HIVE", pointer: "", sceneID: "5B", modelAPointer: "14DD", modelBPointer: "" },
	{ name: "CCW_AUTUMN_ZUBBA_HIVE", pointer: "", sceneID: "5C", modelAPointer: "14DD", modelBPointer: "" },
	{ name: "CCW_SPRING_NABNUTS_HOUSE", pointer: "", sceneID: "5E", modelAPointer: "14DE", modelBPointer: "" },
	{ name: "CCW_SUMMER_NABNUTS_HOUSE", pointer: "", sceneID: "5F", modelAPointer: "14DE", modelBPointer: "" },
	{ name: "CCW_AUTUMN_NABNUTS_HOUSE", pointer: "", sceneID: "60", modelAPointer: "14DE", modelBPointer: "" },
	{ name: "CCW_WINTER_NABNUTS_HOUSE", pointer: "", sceneID: "61", modelAPointer: "14DE", modelBPointer: "" },
	{ name: "CCW_WINTER_HONEYCOMB_ROOM", pointer: "", sceneID: "62", modelAPointer: "14E0", modelBPointer: "" },
	{ name: "CCW_AUTUMN_NABNUTS_WATER_SUPPLY", pointer: "", sceneID: "63", modelAPointer: "14E1", modelBPointer: "14E2" },
	{ name: "CCW_WINTER_NABNUTS_WATER_SUPPLY", pointer: "", sceneID: "64", modelAPointer: "14E1", modelBPointer: "14E2" },
	{ name: "CCW_SPRING_WHIPCRACK_ROOM", pointer: "", sceneID: "65", modelAPointer: "14DF", modelBPointer: "" },
	{ name: "CCW_SUMMER_WHIPCRACK_ROOM", pointer: "", sceneID: "66", modelAPointer: "14DF", modelBPointer: "" },
	{ name: "CCW_AUTUMN_WHIPCRACK_ROOM", pointer: "", sceneID: "67", modelAPointer: "14DF", modelBPointer: "" },
	{ name: "CCW_WINTER_WHIPCRACK_ROOM", pointer: "", sceneID: "68", modelAPointer: "14DF", modelBPointer: "" },
	{ name: "GL_MM_LOBBY", pointer: "", sceneID: "69", modelAPointer: "14F3", modelBPointer: "150B" },
	{ name: "GL_TTC_AND_CC_PUZZLE", pointer: "", sceneID: "6A", modelAPointer: "14F4", modelBPointer: "150C" },
	{ name: "GL_180_NOTE_DOOR", pointer: "", sceneID: "6B", modelAPointer: "14F5", modelBPointer: "1510" },
	{ name: "GL_RED_CAULDRON_ROOM", pointer: "", sceneID: "6C", modelAPointer: "14F6", modelBPointer: "150D" },
	{ name: "GL_TTC_LOBBY", pointer: "", sceneID: "6D", modelAPointer: "14F7", modelBPointer: "1512" },
	{ name: "GL_GV_LOBBY", pointer: "", sceneID: "6E", modelAPointer: "14F8", modelBPointer: "14A8" },
	{ name: "GL_FP_LOBBY", pointer: "", sceneID: "6F", modelAPointer: "14F9", modelBPointer: "14FA" },
	{ name: "GL_GV_PUZZLE", pointer: "", sceneID: "74", modelAPointer: "14FD", modelBPointer: "" },
	{ name: "GL_CC_LOBBY", pointer: "", sceneID: "70", modelAPointer: "14FB", modelBPointer: "1507" },
	{ name: "GL_MMM_LOBBY", pointer: "", sceneID: "75", modelAPointer: "14FE", modelBPointer: "" },
	{ name: "GL_CRYPT", pointer: "", sceneID: "7A", modelAPointer: "14FF", modelBPointer: "" },
	{ name: "GL_STATUE_ROOM", pointer: "", sceneID: "71", modelAPointer: "1500", modelBPointer: "150E" },
	{ name: "GL_BGS_LOBBY", pointer: "", sceneID: "72", modelAPointer: "1501", modelBPointer: "1511" },
	{ name: "GL_640_NOTE_DOOR", pointer: "", sceneID: "76", modelAPointer: "1502", modelBPointer: "1508" },
	{ name: "GL_RBB_LOBBY", pointer: "", sceneID: "77", modelAPointer: "1503", modelBPointer: "1509" },
	{ name: "GL_RBB_AND_MMM_PUZZLE", pointer: "", sceneID: "78", modelAPointer: "1504", modelBPointer: "150A" },
	{ name: "GL_CCW_LOBBY", pointer: "", sceneID: "79", modelAPointer: "1505", modelBPointer: "" },
	{ name: "GL_FF_ENTRANCE", pointer: "", sceneID: "80", modelAPointer: "1506", modelBPointer: "1514" },
	{ name: "GL_FURNACE_FUN", pointer: "", sceneID: "8E", modelAPointer: "14E8", modelBPointer: "" },
	{ name: "GL_DINGPOT", pointer: "", sceneID: "93", modelAPointer: "150F", modelBPointer: "1513" },
	{ name: "GL_BATTLEMENTS", pointer: "", sceneID: "90", modelAPointer: "14FC", modelBPointer: "1515" },
	{ name: "CS_START_NINTENDO", pointer: "", sceneID: "1E", modelAPointer: "149D", modelBPointer: "14A1" },
	{ name: "CS_START_RAREWARE", pointer: "", sceneID: "1F", modelAPointer: "149E", modelBPointer: "14A0" },
	{ name: "CS_INTRO_GL_DINGPOT_1", pointer: "", sceneID: "7B", modelAPointer: "150F", modelBPointer: "" },
	{ name: "CS_INTRO_BANJOS_HOUSE_1", pointer: "", sceneID: "7C", modelAPointer: "14A2", modelBPointer: "" },
	{ name: "CS_SPIRAL_MOUNTAIN_1", pointer: "", sceneID: "7D", modelAPointer: "14CF", modelBPointer: "14D0" },
	{ name: "CS_SPIRAL_MOUNTAIN_2", pointer: "", sceneID: "7E", modelAPointer: "14CF", modelBPointer: "14D0" },
	{ name: "CS_INTRO_GL_DINGPOT_2", pointer: "", sceneID: "81", modelAPointer: "150F", modelBPointer: "" },
	{ name: "CS_ENTERING_GL_MACHINE_ROOM", pointer: "", sceneID: "82", modelAPointer: "150F", modelBPointer: "" },
	{ name: "CS_GAME_OVER_MACHINE_ROOM", pointer: "", sceneID: "83", modelAPointer: "150F", modelBPointer: "" },
	{ name: "CS_UNUSED_MACHINE_ROOM", pointer: "", sceneID: "84", modelAPointer: "150F", modelBPointer: "" },
	{ name: "CS_SPIRAL_MOUNTAIN_3", pointer: "", sceneID: "85", modelAPointer: "14CF", modelBPointer: "14D0" },
	{ name: "CS_SPIRAL_MOUNTAIN_4", pointer: "", sceneID: "86", modelAPointer: "14CF", modelBPointer: "14D0" },
	{ name: "CS_SPIRAL_MOUNTAIN_5", pointer: "", sceneID: "87", modelAPointer: "14A6", modelBPointer: "" },
	{ name: "CS_SPIRAL_MOUNTAIN_6", pointer: "", sceneID: "88", modelAPointer: "14CF", modelBPointer: "14D0" },
	{ name: "CS_INTRO_SPIRAL_7", pointer: "", sceneID: "94", modelAPointer: "14CF", modelBPointer: "14D0" },
	{ name: "CS_END_SPIRAL_MOUNTAIN_1", pointer: "", sceneID: "98", modelAPointer: "149F", modelBPointer: "14A3" },
	{ name: "CS_END_SPIRAL_MOUNTAIN_2", pointer: "", sceneID: "99", modelAPointer: "149F", modelBPointer: "14A3" },
	{ name: "CS_END_ALL_100", pointer: "", sceneID: "95", modelAPointer: "14A9", modelBPointer: "14A5" },
	{ name: "CS_END_NOT_100", pointer: "", sceneID: "20", modelAPointer: "14A9", modelBPointer: "14A5" },
	{ name: "CS_INTRO_BANJOS_HOUSE_2", pointer: "", sceneID: "89", modelAPointer: "14A2", modelBPointer: "14A4" },
	{ name: "CS_INTRO_BANJOS_HOUSE_3", pointer: "", sceneID: "8A", modelAPointer: "14A2", modelBPointer: "14A4" },
	{ name: "CS_END_BEACH_1", pointer: "", sceneID: "96", modelAPointer: "14A9", modelBPointer: "14A5" },
	{ name: "CS_END_BEACH_2", pointer: "", sceneID: "97", modelAPointer: "14A9", modelBPointer: "14A5" },
	{ name: "FILE_SELECT", pointer: "", sceneID: "91", modelAPointer: "14A2", modelBPointer: "14A4" },
];

const BT_Maps = [
	{ name: "SM - Spiral Mountain", pointer: "7998", sceneID: "AF", modelAPointer: "c56c", modelBPointer: "c570" },
	{ name: "SM - behind the waterfall", pointer: "7994", sceneID: "AE", modelAPointer: "c580", modelBPointer: "c584" },
	{ name: "SM - Banjo's House", pointer: "7ca8", sceneID: "0173", modelAPointer: "c574", modelBPointer: "c578" },
	{ name: "SM - Banjo's House (Destroyed)", pointer: "7ca8", sceneID: "0173", modelAPointer: "c5a8", modelBPointer: "" },
	{ name: "SM - Digger Tunnel", pointer: "7be0", sceneID: "0141", modelAPointer: "c598", modelBPointer: "" },
	{ name: "GL - Entrance", pointer: "7990", sceneID: "AD", modelAPointer: "c57c", modelBPointer: "" },
	{ name: "JV - Jinjo Village", pointer: "7be4", sceneID: "0142", modelAPointer: "c88c", modelBPointer: "" },
	{ name: "JV - Bottles house", pointer: "7be8", sceneID: "0143", modelAPointer: "c8c8", modelBPointer: "c8d4" },
	{ name: "JV - King Jingalings throne room", pointer: "7bec", sceneID: "0144", modelAPointer: "c8cc", modelBPointer: "" },
	{ name: "JV - Zombiefied Throne Room", pointer: "7d48", sceneID: "019B", modelAPointer: "c8d0", modelBPointer: "" },
	{ name: "JV - Jinjo's house", pointer: "7bf0", sceneID: "0145", modelAPointer: "c8c4", modelBPointer: "" },
	/*{ name: "JV - Green jinjo's house", pointer: "7bf0", sceneID: "0145", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - Black jinjo's house", pointer: "7bf4", sceneID: "0146", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - Yellow jinjo's house", pointer: "7bf8", sceneID: "0147", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - Blue jinjo's house", pointer: "7bfc", sceneID: "0148", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - Unused jinjo's house", pointer: "7c00", sceneID: "0149", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - Brown jinjo's house", pointer: "7c04", sceneID: "014A", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - Orange jinjo's house", pointer: "7c08", sceneID: "014B", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - Purple jinjo's house", pointer: "7c0c", sceneID: "014C", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - Red jinjo's house", pointer: "7c10", sceneID: "014D", modelAPointer: "c8c4", modelBPointer: "" },
	{ name: "JV - White jinjo's house", pointer: "7c14", sceneID: "014E", modelAPointer: "c8c4", modelBPointer: "" },*/
	{ name: "Mumbo's Skull", pointer: "7c34", sceneID: "0156", modelAPointer: "c58c", modelBPointer: "c590" },
	{ name: "Wumba's Wigwam", pointer: "7c38", sceneID: "0157", modelAPointer: "c588", modelBPointer: "c5a0" },
	{ name: "IOH - Wooden Hollow", pointer: "7c18", sceneID: "014F", modelAPointer: "c890", modelBPointer: "" },
	{ name: "IOH - Heggy's egg shed", pointer: "7c1c", sceneID: "0150", modelAPointer: "c8a4", modelBPointer: "" },
	{ name: "IOH - Jiggywiggy's temple", pointer: "7c20", sceneID: "0151", modelAPointer: "c894", modelBPointer: "" },
	{ name: "IOH - Plateau", pointer: "7c24", sceneID: "0152", modelAPointer: "c898", modelBPointer: "" },
	{ name: "IOH - Honey B's Hive", pointer: "7c28", sceneID: "0153", modelAPointer: "c8c0", modelBPointer: "" },
	{ name: "IOH - Pine Grove", pointer: "7c2c", sceneID: "0154", modelAPointer: "c89c", modelBPointer: "c8a0" },
	{ name: "IOH - Cliff Top", pointer: "7c30", sceneID: "0155", modelAPointer: "c8a8", modelBPointer: "" },
	{ name: "IOH - Wasteland", pointer: "7c44", sceneID: "015A", modelAPointer: "c8ac", modelBPointer: "" },
	{ name: "IOH - Digger Tunnel", pointer: "7c48", sceneID: "015B", modelAPointer: "c8b8", modelBPointer: "" },
	{ name: "IOH - Quagmire", pointer: "7c4c", sceneID: "015C", modelAPointer: "c8b0", modelBPointer: "" },
	{ name: "MT", pointer: "79bc", sceneID: "B8", modelAPointer: "c5b0", modelBPointer: "c5b4" },
	{ name: "MT - Prison Compound", pointer: "79c4", sceneID: "B9", modelAPointer: "c5b8", modelBPointer: "c5bc" },
	{ name: "MT - Columns Vault", pointer: "79c8", sceneID: "BA", modelAPointer: "c5c0", modelBPointer: "" },
	{ name: "MT - Mayan Kickball Stadium", pointer: "79cc", sceneID: "BB", modelAPointer: "c5c4", modelBPointer: "" },
	{ name: "MT - Code Chamber", pointer: "79cc", sceneID: "BC", modelAPointer: "c5c8", modelBPointer: "" },
	{ name: "MT - Jade Snake Grove", pointer: "79ec", sceneID: "C4", modelAPointer: "c5cc", modelBPointer: "c5d0" },
	{ name: "MT - Treasure Chamber", pointer: "79f0", sceneID: "C5", modelAPointer: "c5d4", modelBPointer: "" },
	{ name: "MT - Kickball Arena", pointer: "79f4", sceneID: "C6", modelAPointer: "c5d8", modelBPointer: "" },
	{ name: "MT - kickball arena", pointer: "7a00", sceneID: "00C9", modelAPointer: "c5d8", modelBPointer: "" },
	{ name: "MT - Targitzan's Slighty Sacred Temple", pointer: "7cb8", sceneID: "0177", modelAPointer: "c5dc", modelBPointer: "" },
	{ name: "MT - Inside Targitzan's temple", pointer: "7cbc", sceneID: "0178", modelAPointer: "c5e0", modelBPointer: "" },
	{ name: "MT - Targitzan temple lobby", pointer: "7cc0", sceneID: "0179", modelAPointer: "c5e4", modelBPointer: "" },
	{ name: "MT - Targitzan's Really Sacred Chamber", pointer: "7cc4", sceneID: "017A", modelAPointer: "c5dc", modelBPointer: "" },
	{ name: "GGM", pointer: "79f8", sceneID: "C7", modelAPointer: "c61c", modelBPointer: "c660" },
	{ name: "GGM - fuel depot", pointer: "7a04", sceneID: "00CA", modelAPointer: "c5ec", modelBPointer: "c650" },
	{ name: "GGM - crushing shed", pointer: "7a08", sceneID: "00CB", modelAPointer: "c5f0", modelBPointer: "c628" },
	{ name: "GGM - flooded caves", pointer: "7a0c", sceneID: "00CC", modelAPointer: "c5f4", modelBPointer: "c63c" },
	{ name: "GGM - water storage", pointer: "7a10", sceneID: "00CD", modelAPointer: "c5f8", modelBPointer: "c648" },
	{ name: "GGM - waterfall cavern", pointer: "7a14", sceneID: "00CE", modelAPointer: "c5fc", modelBPointer: "c620" },
	{ name: "GGM - power hut basement", pointer: "7a18", sceneID: "00CF", modelAPointer: "c600", modelBPointer: "c634" },
	{ name: "GGM - chuffy's cab", pointer: "7a1c", sceneID: "00D0", modelAPointer: "c604", modelBPointer: "" },
	{ name: "GGM - inside chuffy's boiler boss", pointer: "7a20", sceneID: "00D1", modelAPointer: "c608", modelBPointer: "" },
	{ name: "GGM - gloomy caverns", pointer: "7a24", sceneID: "00D2", modelAPointer: "c60c", modelBPointer: "c630" },
	{ name: "GGM - generator caverns", pointer: "7a28", sceneID: "00D3", modelAPointer: "c610", modelBPointer: "c640" },
	{ name: "GGM - power hut", pointer: "7a2c", sceneID: "00D4", modelAPointer: "c614", modelBPointer: "c62c" },
	{ name: "GGM - train station", pointer: "7a38", sceneID: "00D7", modelAPointer: "c618", modelBPointer: "" },
	{ name: "GGM - prospectors hut", pointer: "7a3c", sceneID: "00D8", modelAPointer: "c638", modelBPointer: "c664" },
	{ name: "GGM - toxic gas cave", pointer: "7a44", sceneID: "00DA", modelAPointer: "c644", modelBPointer: "" },
	{ name: "GGM - canary cave", pointer: "7a48", sceneID: "00DB", modelAPointer: "c624", modelBPointer: "c64c" },
	{ name: "GGM - Inside Chuffy's wagon", pointer: "7b60", sceneID: "0121", modelAPointer: "c654", modelBPointer: "" },
	{ name: "GGM - water supply pipe", pointer: "7b74", sceneID: "0126", modelAPointer: "c700", modelBPointer: "" },
	{ name: "GGM - Ordnance Shooting Entrance", pointer: "7c68", sceneID: "0163", modelAPointer: "c65c", modelBPointer: "" },
	{ name: "GGM - ordnance storage", pointer: "7a4c", sceneID: "00DC", modelAPointer: "c658", modelBPointer: "" },
	/*{ name: "GGM - Ordnance Shooting Game", pointer: "7c6c", sceneID: "0164", modelAPointer: "", modelBPointer: "" },
	{ name: "GGM - Ordnance Shooting Game Multi", pointer: "7c70", sceneID: "0165", modelAPointer: "", modelBPointer: "" },*/
	{ name: "WW - Witchyworld", pointer: "7a34", sceneID: "00D6", modelAPointer: "c668", modelBPointer: "c698" },
	{ name: "WW - dodgem dome lobby", pointer: "7a50", sceneID: "00DD", modelAPointer: "c68c", modelBPointer: "" },
	/*{ name: "WW - dodgem challenge 1 vs 1", pointer: "7a54", sceneID: "00DE", modelAPointer: "c690", modelBPointer: "" },
	{ name: "WW - dodgem challenge 2 vs 1", pointer: "7a58", sceneID: "00DF", modelAPointer: "c690", modelBPointer: "" },
	{ name: "WW - dodgem challenge 3 vs 1", pointer: "7a5c", sceneID: "00E0", modelAPointer: "c690", modelBPointer: "" },*/
	{ name: "WW - crazy castle stockade", pointer: "7a60", sceneID: "00E1", modelAPointer: "c66c", modelBPointer: "" },
	{ name: "WW - crazy castle lobby", pointer: "7a64", sceneID: "00E2", modelAPointer: "c674", modelBPointer: "" },
	{ name: "WW - crazy castle pump room", pointer: "7a68", sceneID: "00E3", modelAPointer: "c670", modelBPointer: "" },
	{ name: "WW - balloon burst game", pointer: "7a6c", sceneID: "00E4", modelAPointer: "c6a0", modelBPointer: "" },
	{ name: "WW - hoop hurry game", pointer: "7a70", sceneID: "00E5", modelAPointer: "c6a0", modelBPointer: "" },
	{ name: "WW - star spinner", pointer: "7a74", sceneID: "00E6", modelAPointer: "c688", modelBPointer: "c69c" },
	{ name: "WW - the inferno", pointer: "7a78", sceneID: "00E7", modelAPointer: "c678", modelBPointer: "" },
	{ name: "WW - Haunted Caverns", pointer: "7a88", sceneID: "00EB", modelAPointer: "c680", modelBPointer: "" },
	{ name: "WW - Cave of Horrors", pointer: "7a84", sceneID: "00EA", modelAPointer: "c67c", modelBPointer: "" },
	{ name: "WW - Train Station", pointer: "7a8c", sceneID: "00EC", modelAPointer: "c684", modelBPointer: "c6b0" },
	{ name: "WW - Mr. Patch", pointer: "7ac0", sceneID: "00F9", modelAPointer: "c694", modelBPointer: "" },
	/*{ name: "WW - Saucer of Peril", pointer: "7b6c", sceneID: "0124", modelAPointer: "", modelBPointer: "" },
	{ name: "WW - crazy castle stockade (sop)", pointer: "7bc8", sceneID: "013B", modelAPointer: "c66c", modelBPointer: "" },
	{ name: "WW - star spinner (sop)", pointer: "7bcc", sceneID: "013C", modelAPointer: "", modelBPointer: "" },*/
	{ name: "JRL - Town", pointer: "7d78", sceneID: "01A7", modelAPointer: "6e24", modelBPointer: "" }, //c6f8
	{ name: "JRL - Town buildings", pointer: "", sceneID: "01A7", modelAPointer: "6e58", modelBPointer: "" },
	{ name: "JRL - UFO area", pointer: "", sceneID: "", modelAPointer: "6e28", modelBPointer: "" },
	{ name: "JRL - Smugglers Cavern", pointer: "7d74", sceneID: "01A6", modelAPointer: "6e2c", modelBPointer: "6e5c" },
	{ name: "JRL - Atlantis main area", pointer: "7d7c", sceneID: "01A8", modelAPointer: "6e30", modelBPointer: "" },
	{ name: "JRL - Atlantis ship area", pointer: "", sceneID: "", modelAPointer: "6e48", modelBPointer: "" },
	{ name: "JRL - Atlantis Wumba area", pointer: "", sceneID: "", modelAPointer: "6e54", modelBPointer: "6e64" },
	{ name: "JRL - Sea Bottom locker area", pointer: "7d80", sceneID: "01A9", modelAPointer: "6e4c", modelBPointer: "" },
	{ name: "JRL - Sea Bottom big fish area", pointer: "", sceneID: "", modelAPointer: "6e50", modelBPointer: "6e68" },
	{ name: "JRL - Passage UFO to Smugglers", pointer: "", sceneID: "", modelAPointer: "6e34", modelBPointer: "" },
	{ name: "JRL - Passage UFO to Atlantis", pointer: "", sceneID: "", modelAPointer: "6e38", modelBPointer: "" },
	{ name: "JRL - Passage Atlantis to ship", pointer: "", sceneID: "", modelAPointer: "6e3C", modelBPointer: "" },
	{ name: "JRL - Passage ship to locker", pointer: "", sceneID: "", modelAPointer: "6e40", modelBPointer: "" },
	{ name: "JRL - Passage locker to big fish", pointer: "", sceneID: "", modelAPointer: "6e44", modelBPointer: "" },
	{ name: "JRL - Jollys", pointer: "7a90", sceneID: "00ED", modelAPointer: "c6e4", modelBPointer: "c714" },
	//{ name: "JRL - Wumba's Wigwam", pointer: "7b5c", sceneID: "0120", modelAPointer: "c588", modelBPointer: "c5a0" },
	{ name: "JRL - Pawno", pointer: "7a94", sceneID: "00EE", modelAPointer: "c6ec", modelBPointer: "c6f0" },
	{ name: "JRL - Inside UFO", pointer: "7aa0", sceneID: "00F1", modelAPointer: "c6b8", modelBPointer: "c718" },
	{ name: "JRL - Ancient Swimming Baths", pointer: "7aac", sceneID: "00F4", modelAPointer: "c6bc", modelBPointer: "c6c0" },
	{ name: "JRL - Town water box? (LAGGY)", pointer: "", sceneID: "", modelAPointer: "c6f8", modelBPointer: "" },
	//{ name: "JRL - Objects (Beta JRL)", pointer: "7ab0", sceneID: "00F5", modelAPointer: "", modelBPointer: "" },
	{ name: "JRL - Electric Eels Lair", pointer: "7ab4", sceneID: "00F6", modelAPointer: "c6c4", modelBPointer: "c6c8" },
	{ name: "JRL - Seaweed Santchum", pointer: "7ab8", sceneID: "00F7", modelAPointer: "c6cc", modelBPointer: "c6d0" },
	{ name: "JRL - Inside the big fish", pointer: "7abc", sceneID: "00F8", modelAPointer: "c6d4", modelBPointer: "c6d8" },
	{ name: "JRL - Temple of the Fishes", pointer: "7ac4", sceneID: "00FA", modelAPointer: "c6dc", modelBPointer: "c6fc" },
	{ name: "JRL - Lord Woo Fak Fak", pointer: "7acc", sceneID: "00FC", modelAPointer: "c6e8", modelBPointer: "" },
	{ name: "JRL - Blubber's Wave Race Hire", pointer: "7ad8", sceneID: "00FF", modelAPointer: "c6f4", modelBPointer: "" },
	{ name: "JRL - sea bottom cavern", pointer: "7ce0", sceneID: "0181", modelAPointer: "c708", modelBPointer: "" },
	/*{ name: "JRL - submarine multi", pointer: "7ce4", sceneID: "0182", modelAPointer: "", modelBPointer: "" },*/
	{ name: "TDL", pointer: "7b24", sceneID: "0112", modelAPointer: "c720", modelBPointer: "c750" },
	{ name: "TDL - terry's nest", pointer: "7b28", sceneID: "0113", modelAPointer: "c734", modelBPointer: "c75c" },
	{ name: "TDL - train station", pointer: "7b2c", sceneID: "0114", modelAPointer: "c740", modelBPointer: "" },
	{ name: "TDL - oogle boogles cave", pointer: "7b30", sceneID: "0115", modelAPointer: "c744", modelBPointer: "" },
	{ name: "TDL - inside the mountain", pointer: "7b34", sceneID: "0116", modelAPointer: "c72c", modelBPointer: "c730" },
	{ name: "TDL - river passage", pointer: "7b38", sceneID: "0117", modelAPointer: "c738", modelBPointer: "c73c" },
	{ name: "TDL - styracosaurus family cave", pointer: "7b3c", sceneID: "0118", modelAPointer: "c728", modelBPointer: "" },
	{ name: "TDL - unga bunga's cave", pointer: "7b40", sceneID: "0119", modelAPointer: "c748", modelBPointer: "" },
	{ name: "TDL - stomping plains", pointer: "7b44", sceneID: "011A", modelAPointer: "c74c", modelBPointer: "" },
	{ name: "TDL - bonfire caverns", pointer: "7b48", sceneID: "011B", modelAPointer: "c724", modelBPointer: "" },
	{ name: "TDL - Wumba's Wigwam Big (missing)", pointer: "7b64", sceneID: "0122", modelAPointer: "", modelBPointer: "" },
	{ name: "TDL - Inside chompa's belly", pointer: "7b68", sceneID: "0123", modelAPointer: "c608", modelBPointer: "" },
	{ name: "GI - outside", pointer: "7adc", sceneID: "0100", modelAPointer: "c760", modelBPointer: "c7a8" },
	{ name: "GI - inside", pointer: "7ae0", sceneID: "0101", modelAPointer: "c764", modelBPointer: "c7a4" },
	{ name: "GI - Train Station", pointer: "7ae4", sceneID: "0102", modelAPointer: "c77c", modelBPointer: "c7b8" },
	{ name: "GI - workers quarters", pointer: "7ae8", sceneID: "0103", modelAPointer: "c790", modelBPointer: "c7dc" },
	{ name: "GI - trash compactor", pointer: "7aec", sceneID: "0104", modelAPointer: "c780", modelBPointer: "" },
	{ name: "GI - elevator shaft", pointer: "7af0", sceneID: "0105", modelAPointer: "c774", modelBPointer: "" },
	{ name: "GI - floor 2", pointer: "7af4", sceneID: "0106", modelAPointer: "c768", modelBPointer: "c7c4" },
	{ name: "GI - floor 2 (electromagnet chamber)", pointer: "7af8", sceneID: "0107", modelAPointer: "c788", modelBPointer: "" },
	{ name: "GI - floor 3", pointer: "7afc", sceneID: "0108", modelAPointer: "c76C", modelBPointer: "c7c8" },
	{ name: "GI - floor 3 (boiler plant)", pointer: "7b00", sceneID: "0109", modelAPointer: "c784", modelBPointer: "c7d8" },
	{ name: "GI - floor 3 (packing room)", pointer: "7b04", sceneID: "010A", modelAPointer: "c7b0", modelBPointer: "" },
	{ name: "GI - floor 4", pointer: "7b08", sceneID: "010B", modelAPointer: "c770", modelBPointer: "c7cc" },
	{ name: "GI - floor 4 (cable room)", pointer: "7b0c", sceneID: "010C", modelAPointer: "c798", modelBPointer: "" },
	{ name: "GI - floor 4 (quality control)", pointer: "7b10", sceneID: "010D", modelAPointer: "c79c", modelBPointer: "c7ac" },
	{ name: "GI - floor 4 (Clinker's Cavern Lobby)", pointer: "7cf8", sceneID: "0187", modelAPointer: "c7c0", modelBPointer: "c7e0" },
	{ name: "GI - floor 4 (Clinker's Cavern)", pointer: "7c64", sceneID: "0162", modelAPointer: "c7bc", modelBPointer: "" },
	{ name: "GI - floor 5", pointer: "7b14", sceneID: "010E", modelAPointer: "c794", modelBPointer: "" },
	{ name: "GI - basement", pointer: "7b18", sceneID: "010F", modelAPointer: "c778", modelBPointer: "c7d4" },
	{ name: "GI - basement (repair depot)", pointer: "7b1c", sceneID: "0110", modelAPointer: "c7b4", modelBPointer: "" },
	{ name: "GI - basement (waste disposal)", pointer: "7b20", sceneID: "0111", modelAPointer: "c78c", modelBPointer: "c7a0" },
	{ name: "GI - water supply pipe", pointer: "7b70", sceneID: "0125", modelAPointer: "c704", modelBPointer: "" },
	{ name: "HFP - lava side", pointer: "7b78", sceneID: "0127", modelAPointer: "c7ec", modelBPointer: "c7f0" },
	{ name: "HFP - icy side", pointer: "7b7c", sceneID: "0128", modelAPointer: "c7f4", modelBPointer: "c7f8" },
	{ name: "HFP - lava train station", pointer: "7b80", sceneID: "0129", modelAPointer: "c808", modelBPointer: "" },
	{ name: "HFP - ice train station", pointer: "7b84", sceneID: "012A", modelAPointer: "c800", modelBPointer: "c804" },
	{ name: "HFP - chilli billi", pointer: "7b88", sceneID: "012B", modelAPointer: "c81c", modelBPointer: "c82c" },
	{ name: "HFP - chilly willy", pointer: "7b8c", sceneID: "012C", modelAPointer: "c820", modelBPointer: "c830" },
	{ name: "HFP - colosseum kickball stadium lobby", pointer: "7b90", sceneID: "012D", modelAPointer: "c814", modelBPointer: "" },
	/*{ name: "HFP - colosseum kickball stadium - Quarterfinal", pointer: "7b94", sceneID: "012E", modelAPointer: "", modelBPointer: "" },
	{ name: "HFP - colosseum kickball stadium - Semifinal", pointer: "7b98", sceneID: "012F", modelAPointer: "", modelBPointer: "" },
	{ name: "HFP - colosseum kickball stadium - Final", pointer: "7b9c", sceneID: "0130", modelAPointer: "", modelBPointer: "" },*/
	{ name: "HFP - boggy's igloo", pointer: "7ba0", sceneID: "0131", modelAPointer: "c7fc", modelBPointer: "c828" },
	{ name: "HFP - icicle grotto", pointer: "7ba4", sceneID: "0132", modelAPointer: "c80c", modelBPointer: "" },
	{ name: "HFP - inside the volcano", pointer: "7ba8", sceneID: "0133", modelAPointer: "c818", modelBPointer: "" },
	{ name: "CCL", pointer: "7c60", sceneID: "0161", modelAPointer: "c834", modelBPointer: "c854" },
	{ name: "CCL - Cloud Cuckoo Land", pointer: "7bb4", sceneID: "0136", modelAPointer: "c834", modelBPointer: "c854" },
	{ name: "CCL - inside the trashcan", pointer: "7bb8", sceneID: "0137", modelAPointer: "c84c", modelBPointer: "c850" },
	{ name: "CCL - inside the cheesewedge", pointer: "7bbc", sceneID: "0138", modelAPointer: "c848", modelBPointer: "c860" },
	{ name: "CCL - central cavern", pointer: "7bc4", sceneID: "013A", modelAPointer: "c838", modelBPointer: "c858" },
	{ name: "CCL - inside the pot o gold", pointer: "7bd0", sceneID: "013D", modelAPointer: "c83c", modelBPointer: "c840" },
	{ name: "CK - Cauldron Keep", pointer: "7c50", sceneID: "015D", modelAPointer: "c86c", modelBPointer: "c870" },
	{ name: "CK - Gatehouse", pointer: "7c54", sceneID: "015E", modelAPointer: "c878", modelBPointer: "72e4" },
	{ name: "CK - Quiz", pointer: "7c58", sceneID: "015F", modelAPointer: "c87c", modelBPointer: "" },
	{ name: "CK - Gun Chamber", pointer: "7c5c", sceneID: "0160", modelAPointer: "c874", modelBPointer: "" },
	//{ name: "CK - Gun Room Still", pointer: "7c84", sceneID: "016A", modelAPointer: "", modelBPointer: "" },
	{ name: "CK - Final Boss", pointer: "", sceneID: "", modelAPointer: "c884", modelBPointer: "" },
	{ name: "CK - Final Boss Inside", pointer: "", sceneID: "", modelAPointer: "c880", modelBPointer: "" },
	/*{ name: "CK", pointer: "7d44", sceneID: "019A", modelAPointer: "", modelBPointer: "" },
	{ name: "MT - Multi", pointer: "7c74", sceneID: "0166", modelAPointer: "", modelBPointer: "" },
	{ name: "MT - still", pointer: "7c78", sceneID: "0167", modelAPointer: "", modelBPointer: "" },
	{ name: "HFP - Icy side still", pointer: "7c7c", sceneID: "0168", modelAPointer: "", modelBPointer: "" },
	{ name: "Bottles house still", pointer: "7c80", sceneID: "0169", modelAPointer: "", modelBPointer: "" },
	{ name: "GGM", pointer: "7c98", sceneID: "016F", modelAPointer: "", modelBPointer: "" },
	{ name: "GGM", pointer: "7c9c", sceneID: "0170", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Balloons", pointer: "7cc8", sceneID: "017B", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Hoops", pointer: "7ccc", sceneID: "017C", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Packing Game", pointer: "7cd0", sceneID: "017D", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Kickball Arena", pointer: "7cd8", sceneID: "017F", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Kickball Arena 2", pointer: "7cdc", sceneID: "0180", modelAPointer: "", modelBPointer: "" },
	{ name: "TDL - chompa's belly multi", pointer: "7ce8", sceneID: "0183", modelAPointer: "", modelBPointer: "" },
	{ name: "Beta green pipe", pointer: "7cec", sceneID: "0184", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Trash Can", pointer: "7cf0", sceneID: "0185", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Dodgems", pointer: "7cf4", sceneID: "0186", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Bee Hive", pointer: "7cfc", sceneID: "0188", modelAPointer: "", modelBPointer: "" },
	{ name: "MP - Quiz Game", pointer: "7d00", sceneID: "0189", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Game select screen", pointer: "7c3c", sceneID: "0158", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Opening cut scene", pointer: "7c40", sceneID: "0159", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Intro", pointer: "7d08", sceneID: "018B", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Sisters explain BOB", pointer: "7d0c", sceneID: "018C", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - About to Blast Jingaling", pointer: "7d18", sceneID: "018F", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Getting Zapped", pointer: "7d1c", sceneID: "0190", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Zombiefied Throne Room", pointer: "7cd4", sceneID: "017E", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Gained energy from Jingaling", pointer: "7d10", sceneID: "018D", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Party Ended", pointer: "7d20", sceneID: "0191", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Bottles gets home", pointer: "7d24", sceneID: "0192", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Bottles is brought back to life!", pointer: "7d28", sceneID: "0193", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - B and K About to use BOB", pointer: "7d2c", sceneID: "0194", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Lets fix Bottles Next", pointer: "7d30", sceneID: "0195", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Playing with Gruntys Head", pointer: "7d34", sceneID: "0196", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Giving Jingaliong back life", pointer: "7d38", sceneID: "0197", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Jingalings Temple gets back life", pointer: "7d3c", sceneID: "0198", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Jingaling Celebrates that hes back", pointer: "7d40", sceneID: "0199", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Credits", pointer: "7d4c", sceneID: "019C", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Character Parade", pointer: "7d50", sceneID: "019D", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Two Years have Passed", pointer: "7960", sceneID: "A1", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Drill Starts", pointer: "7964", sceneID: "A2", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Drill goes through Boulders", pointer: "7968", sceneID: "A3", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Use Magic to Lift Boulder", pointer: "796c", sceneID: "A4", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Revenge is Mine!", pointer: "7970", sceneID: "A5", modelAPointer: "10510", modelBPointer: "" },
	{ name: "CS - Witches Leave Spiral Mountain", pointer: "7974", sceneID: "A6", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - House Destoryed", pointer: "7978", sceneID: "A7", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Playing Poker", pointer: "797c", sceneID: "A8", modelAPointer: "", modelBPointer: "10518" },
	{ name: "CS - Earthquake!", pointer: "7980", sceneID: "A9", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - It Stopped", pointer: "7984", sceneID: "AA", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Get out of the House!", pointer: "7988", sceneID: "AB", modelAPointer: "", modelBPointer: "" },
	{ name: "CS - Come on!", pointer: "798c", sceneID: "AC", modelAPointer: "", modelBPointer: "" },*/
];
